site_name: Documentation for livi utils
nav:
  - Home: index.md
  - Getting started: Getting started.md
  - Features:
    - Embedding files: feats/FileEmbedding.md

theme:
  name: material
  icon:
    logo: material/heart
  plugins:
    - privacy:
        enabled: true
  palette:
    primary: purple
  highlightjs: true
  hljs_languages:
    - bash
    - javascript
    - typescript
    - markdown

plugins:
  - search
  - callouts

copyright: <a href="https://github.com/LunarWatcher/obsidian-utils/blob/master/LICENSE">All content licensed under the MIT license</a>
repo_url: https://github.com/LunarWatcher/obsidian-utils

markdown_extensions:
  - pymdownx.magiclink
  - admonition
